# Generated by Django 3.1.6 on 2021-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='image',
            field=models.FilePathField(default='mompower.png', path='/image'),
            preserve_default=False,
        ),
    ]
