# Generated by Django 3.1.6 on 2021-02-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='image',
            field=models.FilePathField(path='/images'),
        ),
    ]
